version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: sso_db
    environment:
      MYSQL_ROOT_PASSWORD: w23452345
      MYSQL_DATABASE: sso_provider
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pw23452345"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: sso_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Override DB host to service name in compose network
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: w23452345
      DB_PORT: "3306"
      DB_NAME: sso_provider
      # Cookie config example for local HTTP testing across subdomains
      COOKIE_DOMAIN: 
      COOKIE_SECURE: "false"
      COOKIE_SAMESITE: "Lax"
      COOKIE_HTTPONLY: "false"
      # JWT/Session defaults (override as needed)
      JWT_SECRET_KEY: dev-jwt-secret-change-me
      JWT_ALGORITHM: HS256
      JWT_EXPIRES_MINUTES: "15"
      SESSION_SECRET_KEY: dev-session-secret-change-me
      SITE_NAME: SSO Provider
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/login"]
      interval: 5s
      timeout: 3s
      retries: 20
    # If you want hot-reload in dev, uncomment the volume and change CMD to use --reload
    # volumes:
    #   - ./:/app

volumes:
  db_data:
